[package]
name = "fmainrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
toml = "0.9.10"

[dependencies.sdl2]
version = "0.37.0"
features = ["mixer"]
