# Top level stuff needs to go here
copy_protect_junk = [
    { question = "To Quest for the...?", answer = "LIGHT" },
    { question = "Make haste, but take...?", answer = "HEED" },
    { question = "Scorn murderous...?", answer = "DEED" },
    { question = "Summon the...?", answer = "SIGHT" },
    { question = "Wing forth in...?", answer = "FLIGHT" },
    { question = "Hold fast to your...?", answer = "CREED" },
    { question = "Defy Ye that...?", answer = "BLIGHT" },
    { question = "In black darker than...?", answer = "NIGHT" }
]

[palettes]

[palettes.introcolors]
colors = [
    0x000, 0xFFF, 0xE00, 0xA00, 0xD80, 0xEC0, 0x390, 0x021,
    0xEEB, 0xEDA, 0xEEA, 0xCB8, 0xA95, 0x973, 0x840, 0x620,
    0xA52, 0xC74, 0xD96, 0xFCA, 0x449, 0x444, 0xDC9, 0x668,
    0x33F, 0x888, 0xA60, 0xAAF, 0xBBB, 0xCCF, 0xDDD, 0xEEE
]
[palettes.blackcolors]
colors = [
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
]
[palettes.textcolors]
colors = [
    0x000, 0xFFF, 0xC00, 0xF60, 0x00f, 0xc0f, 0x090, 0xFF0,
    0xf90, 0xf0c, 0xA50, 0xFDB, 0xEB7, 0xCCC, 0x888, 0x444,
    0x000, 0xDB0, 0x740, 0xC70
]
[palettes.pagecolors]
colors = [
    0x000, 0xFFF, 0xE96, 0xB63, 0x631, 0x7BF, 0x333, 0xDB8,
    0x223, 0x445, 0x889, 0xBBC, 0x521, 0x941, 0xF82, 0xFC7,
    0x040, 0x070, 0x0B0, 0x6F6, 0x005, 0x009, 0x00D, 0x37F,
    0xC00, 0xF50, 0xFA0, 0xFF6, 0xEB6, 0xEA5, 0x00F, 0xBDF
]
[palettes.copyjunk]
colors = [
    0x006, 0xFFF, 0x390, 0x000
]

[cursors]

# mouse cursor data
[cursors.bow]
hotspot = { x = 0, y = 0 }
# grudge: TOML 1.1.0 supports mutliline inline tables but it's not well supported yet
[cursors.bow.bitmap]
width = 16
height = 16
depth = 2
stride = 2 # bytes per row
    # copied from sprite_data with SimpleSprite control fields removed and de-interleaved
planes = [
    [   # plane 0
        0x80, 0x06,
        0x60, 0x01,
        0x40, 0x01,
        0x10, 0x03,
        0x08, 0xFE,
        0x05, 0x81,
        0x03, 0x00,
        0x06, 0x01,
        0x0C, 0x80,
        0x08, 0x41,
        0x08, 0x20,
        0x08, 0x11,
        0x08, 0x0C,
        0x88, 0x0F,
        0x98, 0x07,
        0x75, 0x56
    ],
    [   # plane 1
        0x00, 0x00,
        0x00, 0x02,
        0x20, 0x00,
        0x00, 0x00,
        0x00, 0x01,
        0x00, 0x7F,
        0x00, 0x81,
        0x01, 0x01,
        0x02, 0x01,
        0x04, 0x01,
        0x04, 0x01,
        0x04, 0x01,
        0x04, 0x01,
        0x04, 0x01,
        0x44, 0x00,
        0x0F, 0xFC
    ]
]
# bitmap data in binary for reference
# plane 0             plane 1
# 0b1000000000000110, 0b0000000000000000,
# 0b0110000000000001, 0b0000000000000010,
# 0b0100000000000001, 0b0010000000000000,
# 0b0001000000000011, 0b0000000000000000,
# 0b0000100011111110, 0b0000000000000001,
# 0b0000010110000001, 0b0000000001111111,
# 0b0000001100000000, 0b0000000010000001,
# 0b0000011000000001, 0b0000000100000001,
# 0b0000110010000000, 0b0000001000000001,
# 0b0000100001000001, 0b0000010000000001,
# 0b0000100000100000, 0b0000010000000001,
# 0b0000100000010001, 0b0000010000000001,
# 0b0000100000001100, 0b0000010000000001,
# 0b1000100000001111, 0b0000010000000001,
# 0b1001100000000111, 0b0100010000000000,
# 0b0111010101010110, 0b0000111111111100,

[placards]

### hires 640x200 placards

[placards.titletext]
lines = [
    # {x = 56, y = 33, text = "\"The Faery Tale Adventure\""},
    # {x = 40, y = 79, text = "Animation, Programming & Music"},
    # {x = 152, y = 90, text = "by"},
    # {x = 112, y = 101, text = "David Joiner"},
    # {x = 40, y = 160, text = "Copyright 1986 MicroIllusions "}

    # The below lines seem to be from an earlier version, I'm using them
    # because they align properly when rendered to a 640x200 texture
    # They still don't match the hero screen, notably the '&' is "and"
    # on the screenshot <shrug>

    {x = 168, y = 33, text = "\"The Faery Tale Adventure\""},
    {x = 153, y = 74, text = "Animation, Programming & Music"},
    {x = 292, y = 90, text = "by"},
    {x = 250, y = 101, text = "David Joiner"},
    {x = 168, y = 160, text = "Copyright (C) 1986 MicroIllusions "}
]

[placards.copy_junk]
lines = [
    {x = 128, y = 19, text = "So..." },
    {x = 34, y = 65, text = "You, game seeker, would guide the" },
    {x = 10, y = 75, text = "brothers to their destiny? You would" },
    {x = 10, y = 85, text = "aid them and give directions? Answer," },
    {x = 10, y = 95, text = "then, these three questions and prove" },
    {x = 10, y = 105, text = "your fitness to be their advisor:" }
]

### lores 320x200 placards

[placards.julian_start]
lines = [
    {x = 20, y = 28, text = "   \"Rescue the Talisman!\""},
    {x = 20, y = 39, text = "was the Mayor's plea." },
    {x = 20, y = 50, text = "\"Only the Talisman can" },
    {x = 20, y = 61, text = "protect our village from" },
    {x = 20, y = 72, text = "the evil forces of the" },
    {x = 20, y = 83, text = "night.\" And so Julian" },
    {x = 20, y = 94, text = "set out on his quest to" },
    {x = 20, y = 105, text = "recover it." }
]

[placards.julian_dead]
lines = [
    {x = 24, y = 44, text = "Unfortunately for Julian," },
    {x = 24, y = 55, text = "his luck had run out." },
    {x = 24, y = 66, text = "Many months passed and" },
    {x = 24, y = 77, text = "Julian did not return..." }
]

[placards.phillip_start]
lines = [
    {x = 40, y = 44, text = "So Phillip set out," },
    {x = 40, y = 55, text = "determined to find his" },
    {x = 40, y = 66, text = "brother and complete" },
    {x = 40, y = 77, text = "the quest." }
]

[placards.phillip_dead]
lines = [
    {x = 24, y = 44, text = "But sadly, Phillip's" },
    {x = 24, y = 55, text = "cleverness could not save" },
    {x = 24, y = 66, text = "him from the same fate" },
    {x = 24, y = 77, text = "as his older brother." }
]

[placards.kevin_start]
lines = [
    {x = 30, y = 30, text = "So Kevin took up the" },
    {x = 30, y = 41, text = "quest, risking all, for" },
    {x = 30, y = 52, text = "the village had grown" },
    {x = 30, y = 63, text = "desperate. Young and" },
    {x = 30, y = 74, text = "inexperienced, his" },
    {x = 30, y = 85, text = "chances did not look" },
    {x = 30, y = 96, text = "good." }
]

[placards.kevin_dead]
lines = [
    {x = 20, y = 31, text = "And so ends our sad tale." },
    {x = 25, y = 45, text = "The Lesson of the Story:" },
    {x = 66, y = 88, text = "Stay at Home!" }
]

[placards.player_win]
lines = [
    {x = 28, y = 32, text = "Having defeated the" },
    {x = 28, y = 43, text = "villanous Necromancer" },
    {x = 28, y = 54, text = "and recovered the" },
    {x = 28, y = 65, text = "Talisman, %" },
    {x = 28, y = 76, text = "returned to Marheim" },
    {x = 28, y = 87, text = "where he wed the" },
    {x = 28, y = 98, text = "princess..." }
]

[placards.rescue_katra]
lines = [
    {x = 21, y = 26, text = "% had rescued Katra," },
    {x = 21, y = 37, text = "Princess of Marheim." },
    {x = 21, y = 48, text = "Though they had pledged" },
    {x = 21, y = 59, text = "their love for each, " },
    {x = 21, y = 70, text = "other, % knew that" },
    {x = 21, y = 81, text = " his quest could not" },
    {x = 21, y = 92, text = "be forsaken." }
]

[placards.rescue_karla]
lines = [
    {x = 21, y = 33, text = "% had rescued Karla" },
    {x = 21, y = 44, text = "(Katra's sister), Princess" },
    {x = 21, y = 55, text = "of Marheim. Though they" },
    {x = 21, y = 66, text = "had pledged their love" },
    {x = 21, y = 77, text = "for each other, %" },
    {x = 21, y = 88, text = "knew that his quest" },
    {x = 21, y = 99, text = "could not be forsaken." }
]

[placards.rescue_kandy]
lines = [
    {x = 21, y = 26, text = "% had rescued Kandy" },
    {x = 21, y = 37, text = "(Katra's and Karla's" },
    {x = 21, y = 48, text = "sister), Princess of" },
    {x = 21, y = 59, text = "Marheim. Though they had" },
    {x = 21, y = 70, text = "pledged their love for" },
    {x = 21, y = 81, text = "each other, % knew " },
    {x = 21, y = 92, text = "that his quest could" },
    {x = 21, y = 103, text = "not be forsaken." }
]

[placards.princess_home]
lines = [
    {x = 71, y = 37, text = "After seeing the" },
    {x = 35, y = 48, text = "princess safely to her" },
    {x = 35, y = 59, text = "home city, and with a" },
    {x = 35, y = 70, text = "king's gift in gold," },
    {x = 35, y = 81, text = "% once more set" },
    {x = 35, y = 92, text = "out on his quest." }
]


[fonts]

[fonts.amber]
file = "game/fonts/amber.font"

[fonts.topaz]
file = "game/fonts/topaz.font"

[images]

# Book pages
# book background image
[images.page0]
file = "game/page0"

# Julian's portrait
[images.p1a]
file = "game/p1a"

# Julian bio
[images.p1b]
file = "game/p1b"

# Phillip's portrait
[images.p2a]
file = "game/p2a"

# Phillip bio
[images.p2b]
file = "game/p2b"

# Kevin's portrait
[images.p3a]
file = "game/p3a"

# Kevin bio
[images.p3b]
file = "game/p3b"

# Background image for text scroll area
[images.hiscreen]
file = "game/hiscreen"

# You can only see this if you win!
[images.winpic]
file = "game/winpic"
